In [28]:
import pandas as pd

In [29]:
filename = f"../results/results_2003.csv"
log_df = pd.read_csv(filename)

We exclude the first 1k executions to try and fill all the cache, to then have a fully comparable set of queries

In [30]:
log_df = log_df.iloc[100:]

In [31]:
log_df.shape

(900, 8)

In [32]:
log_df.head()

,Plan,Planning Time,Triggers,Execution Time,QueryType,NumRows,FullQuery,QueryParams
100,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",1.226,[],500.996,4,1075,"SELECT g.key, g.value->>'ra', g.value->>'dec',...","{'objidlist': '1237660979579257715, 1237648704..."
101,"{'Node Type': 'Limit', 'Parallel Aware': False...",0.937,[],0.402,1,1,"SELECT p.key, p.value->>'run', p.value->>'reru...","{'objidlist': '1237656563820135091, 1237656512..."
102,"{'Node Type': 'Limit', 'Parallel Aware': False...",0.532,[],0.386,1,1,"SELECT p.key, p.value->>'run', p.value->>'reru...","{'objidlist': '1237665440451134067, 1237663530..."
103,"{'Node Type': 'Limit', 'Parallel Aware': False...",0.582,[],0.414,1,1,"SELECT p.key, p.value->>'run', p.value->>'reru...","{'objidlist': '1237680266665657292, 1237654601..."
104,"{'Node Type': 'Limit', 'Parallel Aware': False...",1.088,[],0.540,1,1,"SELECT p.key, p.value->>'run', p.value->>'reru...","{'objidlist': '1237651735771415319, 1237646549..."

In [34]:
query_count_summary = log_df['QueryType'].value_counts().reset_index()
query_count_summary.columns = ['QueryType', 'Count']
total_count = query_count_summary['Count'].sum()
query_count_summary['Percentage'] = (query_count_summary['Count'] / total_count) * 100

query_count_summary

   QueryType  Count  Percentage
0          1    543   60.333333
1          2    203   22.555556
2          4    100   11.111111
3          3     42    4.666667
4          5     12    1.333333

In [35]:
execution_time_summary = log_df.groupby('QueryType')['Execution Time'].sum().reset_index()
total_execution_time = execution_time_summary['Execution Time'].sum()
execution_time_summary['Percentage'] = (execution_time_summary['Execution Time'] / total_execution_time) * 100


execution_time_summary

   QueryType  Execution Time  Percentage
0          1         554.147    0.745593
1          2       38199.930   51.397203
2          3       12349.153   16.615526
3          4       23219.479   31.241321
4          5           0.266    0.000358

In [37]:
summary = log_df.groupby('QueryType').agg(
    Total_Execution_Time=('Execution Time', 'sum'),
    Execution_Count=('QueryType', 'count'),
    Mean_Execution_Time=('Execution Time', 'mean'),
    Std_Dev_Execution_Time=('Execution Time', 'std')
)

summary['Total_Execution_Percentage'] = (summary['Total_Execution_Time'] / summary['Total_Execution_Time'].sum()) * 100
# summary['Mean_Execution_Time_Percentage'] = (summary['Mean_Execution_Time'] / summary['Mean_Execution_Time'].sum()) * 100

summary

,Total_Execution_Time,Execution_Count,Mean_Execution_Time,Std_Dev_Execution_Time,Total_Execution_Percentage
QueryType,,,,,
1,554.147,543,1.020529,1.264669,0.745593
2,38199.930,203,188.176995,111.638294,51.397203
3,12349.153,42,294.027452,165.750240,16.615526
4,23219.479,100,232.194790,152.636406,31.241321
5,0.266,12,0.022167,0.012698,0.000358

In [40]:
log_df['Execution Time'].sum()

803003.3899999999

In [18]:
log_df[log_df['QueryType'] == 4]

,Plan,Planning Time,Triggers,Execution Time,QueryType,NumRows,FullQuery,QueryParams
1020,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",1.171,[],9.199,4,0,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582094734185988244, 58209348490..."
1040,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",0.830,[],5.451,4,0,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582093502079434957, 58209597113..."
1071,"{'Node Type': 'Gather', 'Parallel Aware': Fals...",1.916,[],12.768,4,0,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582095970600747090, 58209348380..."
1124,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",0.407,[],4.111,4,314,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582095148651905157, 58237701500..."
1144,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",1.137,[],16.829,4,1700,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582094698749362400, 58265900054..."
...,...,...,...,...,...,...,...,...
10943,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",0.515,[],6.564,4,635,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582096316872654968, 58209597059..."
10953,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",0.445,[],2.761,4,39,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582096318491459696, 58209350098..."
10972,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",0.321,[],1.886,4,93,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582094742234398780, 58209473310..."
10976,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",1.170,[],9.566,4,221,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582095970056012126, 58209350101..."
10982,"{'Node Type': 'Nested Loop', 'Parallel Aware':...",0.379,[],2.797,4,104,"SELECT g.objID, g.data ->'ra' AS ra, g.data ->...","{'objidlist': '582096482227060843, 58209631956..."

In [19]:
print(log_df['Plan'][1017])

{'Node Type': 'Result', 'Parallel Aware': False, 'Async Capable': False, 'Startup Cost': 0.35, 'Total Cost': 864.05, 'Plan Rows': 143, 'Plan Width': 256, 'Actual Startup Time': 0.068, 'Actual Total Time': 1.156, 'Actual Rows': 142, 'Actual Loops': 1, 'Plans': [{'Node Type': 'Append', 'Parent Relationship': 'Outer', 'Parallel Aware': False, 'Async Capable': False, 'Startup Cost': 0.35, 'Total Cost': 859.76, 'Plan Rows': 143, 'Plan Width': 412, 'Actual Startup Time': 0.058, 'Actual Total Time': 0.589, 'Actual Rows': 142, 'Actual Loops': 1, 'Subplans Removed': 0, 'Plans': [{'Node Type': 'Seq Scan', 'Parent Relationship': 'Member', 'Parallel Aware': False, 'Async Capable': False, 'Relation Name': 'photoprimarymain', 'Alias': 'p_1', 'Startup Cost': 0.35, 'Total Cost': 0.35, 'Plan Rows': 1, 'Plan Width': 32, 'Actual Startup Time': 0.004, 'Actual Total Time': 0.005, 'Actual Rows': 0, 'Actual Loops': 1, 'Filter': "(objid = ANY ('{582094699282825328,582377505200406742,582093501545382034,582377466504085747,582094734183825531,582096318502273243,582093499929264395,582094734182776888,582377553480515918,582093483292885154,582093483803148430,582093484882985036,582094699278237867,582093500458598485,582093483304157630,582095575996432431,582093484903497918,582096316878815319,582094742234857568,582093453769703988,582094740627980474,582095148655968312,582093499932606623,582093482751295686,582093502085857438,582094697669329019,582377504626049126,582093482211737782,582094742774022327,582093501024895186,582096276071907547,582096482493726844,582093501536927750,582096317949345823,582093484357255355,582093483814879380,582096601414369297,582093484338184303,582094733104971906,582094732567511104,582095574918955354,582093500466725078,582093500466528416,582377467576320255,582093484357714082,582093484882591795,582094699824873647,582377551868199139,582093482733600948,582377466505855202,582093484377375006,582377015543398621,582377551330738403,582093483296358683,582095969519796479,582095970596028597,582094698206199924,582660327681295220,582093483813503220,582096482225619111,582096317428203643,582093500478849239,582095969528250502,582094699285381247,582094741162033312,582095150795128929,582093499935686994,582659001637667015,582093483301405102,582377016074567846,582094742234988715,582093499944796291,582377478853689457,582377017153618077,582096316888056028,582093482764534089,582093501029810500,582093500468166830,582096276068827564,582093483841749629,582096319040782491,582093484891242542,582095969527201869,582094700359778453,582093484887048251,582377465967149512,582093484907430091,582093501530833102,582377015005216893,582093501001302156,582093500468166726,582377467044298800,582377467043709237,582096317424664805,582096481690124441,582377505187299524,582377564213936331,582377506234630524,582094743311351979,582093499948990721,582093499937390816,582096317944234127,582093500991602998,582093499916615830,582093484345000174,582093501015326981,582093483829035030,582377479388922131,582094700355584163,582659002426720452,582093501543022647,582094741692940359,582093499410940037,582096317420601425,582093484907036786,582093499406221585,582093483295703264,582093501545185433,582096276069744765,582093484906315974,582377015538352288,582093482747429002,582093484376391992,582093482764206553,582093483284103302,582096482231517442,582377015537434753,582096494042743247,582093483265753231,582094741161508919,582093502089396373,582093482727702694,582093484338774066,582377015002923207,582093501545447649,582093500485861553,582377015541825745,582096316871606282,582377504629981235,582093483280957577,582094733108248723,582377467577565418}'::bigint[]))", 'Rows Removed by Filter': 0}, {'Node Type': 'Index Scan', 'Parent Relationship': 'Member', 'Parallel Aware': False, 'Async Capable': False, 'Scan Direction': 'Forward', 'Index Name': 'pk_photoprimary', 'Relation Name': 'photoprimary', 'Alias': 'p_2', 'Startup Cost': 0.29, 'Total Cost': 858.69, 'Plan Rows': 142, 'Plan Width': 415, 'Actual Startup Time': 0.053, 'Actual Total Time': 0.563, 'Actual Rows': 142, 'Actual Loops': 1, 'Index Cond': "(objid = ANY ('{582094699282825328,582377505200406742,582093501545382034,582377466504085747,582094734183825531,582096318502273243,582093499929264395,582094734182776888,582377553480515918,582093483292885154,582093483803148430,582093484882985036,582094699278237867,582093500458598485,582093483304157630,582095575996432431,582093484903497918,582096316878815319,582094742234857568,582093453769703988,582094740627980474,582095148655968312,582093499932606623,582093482751295686,582093502085857438,582094697669329019,582377504626049126,582093482211737782,582094742774022327,582093501024895186,582096276071907547,582096482493726844,582093501536927750,582096317949345823,582093484357255355,582093483814879380,582096601414369297,582093484338184303,582094733104971906,582094732567511104,582095574918955354,582093500466725078,582093500466528416,582377467576320255,582093484357714082,582093484882591795,582094699824873647,582377551868199139,582093482733600948,582377466505855202,582093484377375006,582377015543398621,582377551330738403,582093483296358683,582095969519796479,582095970596028597,582094698206199924,582660327681295220,582093483813503220,582096482225619111,582096317428203643,582093500478849239,582095969528250502,582094699285381247,582094741162033312,582095150795128929,582093499935686994,582659001637667015,582093483301405102,582377016074567846,582094742234988715,582093499944796291,582377478853689457,582377017153618077,582096316888056028,582093482764534089,582093501029810500,582093500468166830,582096276068827564,582093483841749629,582096319040782491,582093484891242542,582095969527201869,582094700359778453,582093484887048251,582377465967149512,582093484907430091,582093501530833102,582377015005216893,582093501001302156,582093500468166726,582377467044298800,582377467043709237,582096317424664805,582096481690124441,582377505187299524,582377564213936331,582377506234630524,582094743311351979,582093499948990721,582093499937390816,582096317944234127,582093500991602998,582093499916615830,582093484345000174,582093501015326981,582093483829035030,582377479388922131,582094700355584163,582659002426720452,582093501543022647,582094741692940359,582093499410940037,582096317420601425,582093484907036786,582093499406221585,582093483295703264,582093501545185433,582096276069744765,582093484906315974,582377015538352288,582093482747429002,582093484376391992,582093482764206553,582093483284103302,582096482231517442,582377015537434753,582096494042743247,582093483265753231,582094741161508919,582093502089396373,582093482727702694,582093484338774066,582377015002923207,582093501545447649,582093500485861553,582377015541825745,582096316871606282,582377504629981235,582093483280957577,582094733108248723,582377467577565418}'::bigint[]))", 'Rows Removed by Index Recheck': 0}]}]}

In [20]:
print(log_df['FullQuery'][1033])

SELECT p.objID, p.data->'run' AS run, p.data->'rerun' AS rerun, p.data->'camcol' AS camcol, p.data->'field' AS field, p.data->'obj' AS obj, p.data->'type' AS type, p.data->'ra' AS ra, p.data->'dec' AS dec, p.data->'u' AS u, p.data->'g' AS g, p.data->'r' AS r, p.data->'i' AS i, p.data->'z' AS z, p.data->'err_u' AS err_u, p.data->'err_g' AS err_g, p.data->'err_r' AS err_r, p.data->'err_i' AS err_i, p.data->'err_z' AS err_z FROM  db_2003_ns.PhotoPrimary AS p WHERE  p.objID IN (582377015002136672, 582096317428990192, 582096480616382593, 582093501025681813, 582093501535224026, 582096317943578769, 582093484378554552, 582093501013884993, 582093484881477806, 582093499947417830, 582094699282235660, 582096317422305544, 582093484875710652, 582094699278368913, 582096317952884929, 582093483297931390, 582095575458775339, 582659002148651320, 582093501020438723, 582093482742972675, 582093501009625111, 582093499406155874, 582093483276566606, 582094732037128356, 582659001084215506, 582095970062172269, 582095971138142366, 582377551868854293, 582093484905922726, 582093482764337461, 582093500999925895, 582095968991052141, 582096482231844994, 582095574383657242, 582094699820482745, 582093500996911496, 582377504630833382, 582377016611242168, 582095575991910722, 582094733642105046, 582377017154076844, 582093499410350287, 582093499392131162, 582093501565894770, 582093483304878669, 582377551867019591, 582093483838210445, 582093483803410544, 582094741700870303, 582096494041038862, 582377551867281527, 582093501005627464, 582378007136567560, 582093501031186494, 582093500484288541, 582093501564649738, 582093499932344568, 582093499390623768, 582093499934965943, 582377505697169779, 582095970057257048, 582094741701132425, 582093482743562882, 582093501017227329, 582095969523794075, 582094698743201923, 582093499913339474, 582093483832705230, 582095969517830427, 582096317419421869, 582093499942568126, 582093482201579590, 582093484882460813, 582377467040694473, 582093483820777623, 582094733110345838, 582094732569411698, 582093502079303782, 582093499928215744, 582093484903170333, 582095970596159670, 582093484343689239, 582093500467642392, 582096601413386279, 582094698749886590, 582094743304470608, 582095970066563153, 582377504632078488, 582377478852772124, 582093484880298110, 582093482207412360, 582093483821695190, 582093482736943230, 582093484368658708, 582093482731110562, 582093483827069053, 582094733643153567, 582377504632209551, 582095971137683468, 582093483264835712, 582093501568057612, 582377505737146676, 582093482737795079, 582095970054373654, 582093499416314100, 582093483813503006, 582093501550428313, 582096317950722123, 582093482756800714, 582093500483436767, 582093484898386071, 582093482746576982, 582094742766223412, 582095149727088723, 582093499948269862, 582377505194377264, 582093482760142945, 582093502082842710, 582096481157578902, 582093483300421892, 582658979599090031, 582093500470460631, 582094734185922676, 582093499940339966, 582095971134996622, 582094732570198104, 582096482228764862, 582094743305519206, 582377552405004607, 582096275533529117, 582093483273224297, 582378007134077372, 582093484888817756, 582093482214686869, 582094700361482409, 582096317419552971, 582094734184939674, 582095970596093984, 582096275532415245, 582093482763288914, 582093482762043417, 582094732030836816, 582094733111590952, 582659001082445996, 582093502094573747, 582093484905726208, 582093482195157183, 582093484369707233, 582096319560482933, 582377554013651188, 582093501560521023, 582093500998746159, 582093484907298918, 582093483271127075, 582095969530151167, 582377016074043426, 582095971672653883, 582377017148309652, 582093499404714186, 582096317420667070, 582095150266318989, 582093482766041616, 582093500493072202, 582377552402776274, 582093482764140651, 582093482763288811, 582093499386364037, 582377014459498608, 582093484360204400, 582093484371542185, 582095970603434205, 582094732039225451, 582377478853230865, 582093500991930391, 582377015533436961, 582093502096539766, 582093501540991190, 582093484906250491, 582093484349194340, 582659001627967503, 582094733641252958, 582093482213769262, 582096317945413866, 582377565825597699, 582094741695627325, 582093500454600953, 582377554015223881, 582093483281612978, 582094698213081269, 582094697668739219, 582096319028658420, 582093501012115591, 582093483825168509, 582093499921662176, 582095574919610696, 582093484345589830, 582093484898517167, 582377551333425197, 582093484376719484, 582094732031951104, 582093501564059952, 582094699820286023, 582096481156857911, 582093484891635899, 582095970060795909, 582093453233357318, 582093501567860986, 582093484341854742, 582096319565529173, 582377505737408727, 582095574382215231, 582093482735436066, 582093483274600608, 582095150805614744, 582093483266277520, 582093499924414733, 582093484875251847, 582093500475834427, 582093500457156853, 582094740625621177, 582096317944889473, 582093501550755963, 582093483807604914, 582093484880101388, 582093501026795795, 582094741158953066, 582093483280171088, 582094700357025927, 582096480616317367, 582093502088872098, 582093483837555144, 582093483281416286, 582093483291639816, 582093483295244506, 582093499403665675, 582094733105889469, 582093500996911278, 582377551331524850, 582093482742906915, 582659001088606347, 582093501017948316, 582095971675275438, 582093483837948107, 582093483803476204, 582093499935817961, 582095150265860216, 582093500990357740, 582094700359909571, 582377566362271964, 582096276071973258, 582093482757980286, 582093501013557480, 582093499395277035, 582093499406811359, 582093484365447294, 582095149731545141, 582094734186446962, 582094699283415045, 582095969525956881, 582093482211344569, 582093483273945184, 582093501003530380, 582095971676717188, 582093483290984636, 582093482209509591, 582095969521238280, 582093483289411793, 582377014469132464, 582093500471246959, 582096482229420238, 582093484890062944, 582095971673964741, 582093501008511201, 582096317943185679, 582094742234333353, 582095969523073207, 582094699288330650, 582093502097719528, 582093499408973847, 582093482751295735, 582659001085329639, 582093500997959843, 582096494043136350, 582094700355977388, 582093501031710929, 582093501546627208, 582096494039990521, 582377506235875472, 582093499415068811, 582093499405500516, 582094741164851394, 582095970602778818, 582096317406314626, 582093482744545386, 582377505194311800, 582094732032868470, 582377466504544361, 582096318491459696, 582093483265032352, 582094742771794006, 582093501027909703, 582659001626984670, 582093483264835735, 582093500458664236, 582093483801379049, 582096274997641575, 582093483298390248, 582093483277615210, 582094733640663221, 582093482744545379, 582093484374425978, 582377505196802403, 582094740624048301, 582094743306960956, 582377504645120176, 582095971130540301, 582093501024960762, 582093483269226627, 582093500487368954, 582377505734590661, 582096494579351775, 582093482741530787, 582093482209443966, 582095971130016126, 582377505188741405, 582093483803148417, 582093501556850847, 582093502089330870, 582095149194215631, 582095970597535978, 582093501550035028, 582095149192183860, 582096481694384207, 582095971129164038, 582093483803082758, 582377466505724241, 582096480078332053, 582093483829690646, 582096601413517316, 582658979599155666, 582093483274731706, 582093500452634779, 582095971128312293, 582095969522484071, 582096319563235358, 582093501031252010, 582093483828052236, 582659000548917359, 582095969522680148, 582377014459433111, 582096482227650778, 582093483294851313, 582094699286560946, 582093482205773921, 582094734722072602, 582093483267653739, 582094743305519215, 582096276072562859, 582094742237085869, 582093501541122222, 582093483805114453, 582377016076665024, 582094743300735080, 582095970601468249, 582093484362105063, 582094698744840341, 582096274994364761, 582377016077254863, 582096317420601502, 582094732576489602, 582093482212851723, 582096317966123202, 582093482201710718, 582093483804262515, 582377466506248489, 582095969523007736, 582377506240135408, 582096276068696629, 582094742228566124, 582093499397439574, 582093482213638304, 582377505187299431, 582093482749657205, 582093499934900351, 582093483819794565, 582093501557178567, 582377505198506362, 582096494578827600, 582093501023387999, 582093484340543594, 582093483304288376, 582095971677175971, 582094700357877770, 582096316874883218, 582096494040842505, 582377553481302066, 582094734176026736, 582377504627294402, 582094699817992381, 582093484908806273, 582093500472819896, 582093499923693758, 582095971136110718, 582377467041480759, 582093483265949713, 582093502084153571, 582093499386036336, 582096317944037436, 582093500482519179, 582377552402448664, 582093483292230834, 582377478855328117, 582095968993149122, 582659000549441619, 582377016613798183, 582377017143197740, 582096317407494333, 582093484893143047, 582377015543464209, 582095148656164941, 582095148655771719, 582093484881674502, 582093484340805726, 582096493505675755, 582096317406642380, 582093483271913612, 582093482750640336, 582095574917513676, 582096275533857315, 582093501020373245, 582093482766172431, 582093483266277528, 582094698209083571, 582378007139844351, 582093501538894035, 582377505735901312, 582096317418045550, 582096275533529476, 582093483806097550, 582094734715191435, 582096494579417506, 582096317945872542, 582093501002809534, 582095574921314527, 582659002148651349, 582094699819237567, 582093502087823569, 582093499415658651, 582093484908806188, 582093501559734778, 582093500999925885, 582093500989702415, 582095970595897566, 582093501003530413, 582093483296751674, 582093499917402365, 582093501525067126, 582377467041481034, 582096316879798446, 582093484887834716, 582377504644857951, 582093453233815847, 582093500474064922, 582093483804065965, 582095150267236568, 582093501018341539, 582094699818647730, 582093482739433556, 582377553476452564, 582096317406576848, 582659002161496109, 582093499406287081, 582094733110804644, 582093499944272635, 582093484369051730, 582094733108576446, 582377506798567561, 582095151340978193, 582095971675734141, 582093499952791688, 582093484355026985, 582096317948756047, 582093501540204626, 582095150804238429, 582096494042546338, 582095150801879158, 582093484884885642, 582095969519075500, 582093483807080456, 582094700361089140, 582377467042857261, 582094698742677610, 582093499404714005, 582096274998165838, 582377015538745558, 582095575995580696, 582093484885999755, 582096275532153189, 582095149195133078, 582093482758504588, 582093499940339940, 582093482215014642, 582093483837358384, 582093499392524447, 582096276071121143, 582094734181269596, 582093482731765914, 582094741691957306, 582377504623690029, 582093483841618408, 582096273924882742, 582093499926970572, 582093500467904541, 582093501005824204, 582094698207772805, 582094742235578556, 582094732574720158, 582093499926905045, 582093482221502512, 582096316881764387, 582094733103726680, 582094742230597760, 582093482762109133, 582659002165231759, 582094698211901584, 582094698210459675, 582093502083301662, 582096319018762401, 582093501029744920, 582093484886392915, 582094697674440786, 582093501556064319, 582093499917533201, 582093500463120547, 582093499923824776, 582094732033065022, 582377467041808729, 582377506234237290, 582094733105955002, 582093499411857606, 582094740626210978, 582095970067087467, 582093482752999592, 582093482757783835, 582096481156530287, 582094699822448668, 582094732034769027, 582093500993830980, 582094698745692350, 582093500476358864, 582093501002154111, 582093502079107395, 582094699279220900, 582377015005348001, 582093483277287438, 582094734714077358, 582094699278565679, 582093501023846663, 582093484876562502, 582093501542695040, 582096316879470750, 582094697671295167, 582095971140501703, 582093500990423273, 582093501003464884, 582096601418563619, 582095149194477723, 582377551869837978, 582093500475506909, 582093483294064824, 582093483266539714, 582094742230270024, 582093484354175059, 582377017148571802, 582095149192249540, 582377551866036369, 582377015543595189, 582377467040104655, 582377506237907162, 582377505199161827, 582094732569935998, 582093501563404313, 582093483282726930, 582377479390167159, 582093484896289001, 582377014469066774, 582094740622671954, 582093483278925990, 582094698209673316, 582096481156006075, 582659001082904748, 582377551330803879, 582093499386298562, 582377504120569883, 582093483292098563, 582096494041759982, 582093484347293836, 582094733641711844, 582093499409039450, 582094733110280378, 582096319564415092, 582093500463775774, 582093501539745950, 582095971675078759, 582377564214657220, 582093482763616706, 582093501011067114, 582093482759028952, 582093500467052631, 582093500484354061, 582093482215276728, 582095970597797988, 582093483269816461, 582659003242643467, 582377564750872721, 582093499414937767, 582093482753327267, 582096319569854595, 582378007134667199, 582095575995842589, 582095149721518259, 582093500493463638, 582093499416641754, 582094742234791940, 582096494580400649, 582093499392196803, 582093499926511764, 582093501564191145, 582093501558161620, 582094734179106948, 582094698740252863, 582096601412272311, 582659002146750833, 582377478852116691, 582093499917009136, 582093483837555025, 582377479389577271, 582094742230663422, 582094742764322920, 582096316882944154, 582093499934769352, 582096317967171630, 582377565826384042, 582093483281547463, 582096480081805469, 582095575455039668, 582377016070439037, 582095970601468147, 582095575457136920, 582096275535626510, 582094734716108963, 582093482761519609, 582093499402027182, 582094697667297497, 582093501022732531, 582093483830214762, 582093484878725255, 582094734717747231, 582093482765189494, 582093483271258260, 582093483289542822, 582094741701329167, 582093483838079183, 582094733647085726, 582094743306829890, 582093483830739191, 582094733111197916, 582096494579679427, 582093499384135864, 582095971673374937, 582093484376850782, 582095148647776349, 582095971134406787, 582094734187102348, 582093499937194263, 582377504630767678, 582093484360073327, 582095971672326371, 582093500991406282, 582659002164052124, 582093484349259949, 582093482765910297, 582094700354273459, 582095969523728887, 582094699823759523, 582095149725778066, 582096316893757654, 582093501527883781, 582096481694908557, 582093483281023090, 582093501531816052, 582094732031885438, 582096481419985144, 582093484904808557, 582094742236954831, 582093501555671255, 582093500482060451, 582096480615530525, 582093483290525766, 582096317430300957, 582377015001612504, 582093500473082010, 582093483824841001, 582377566365876267, 582094732030902347, 582093483812716642, 582094732039225420, 582093483280236660, 582095148647907595, 582094741696807023, 582093501533782267, 582659000549179525, 582096481157972068, 582094734177140841, 582093483822415979, 582093484889407771, 582095148658262262, 582377015533174901, 582377015541235718, 582093482198892757, 582093500990030146, 582094733640204404, 582093499922383036, 582093500453945548, 582094733643087953, 582093500450800254, 582093499934965842, 582377565828284687, 582093484368789719, 582096317426958435, 582093500469870777, 582659001081397400, 582093499390296190, 582093501561307388, 582659000547999858, 582094733640663182, 582093484879249544, 582094740622540881, 582094734178254948, 582093499924021556, 582096317427876118, 582095969519862101, 582093501014999177, 582377014468018233, 582093499406418011, 582096316872589463, 582095574383394876, 582094699817533483, 582093484906905914, 582095968991510734, 582096481156530327, 582377506800009520, 582377015541104811, 582094733110804662, 582093502095884488, 582093483276173371, 582377564215378173, 582093482201973460, 582093483274993756, 582659001097650195, 582093499951874095, 582093500459974807, 582093501563666649, 582095574385361238, 582093482758963354, 582093501009494074, 582093499953447032, 582377506236334283, 582377506234171611, 582093484377178199, 582094698744840331, 582093501539614897, 582093482751951084, 582093483838669023, 582093499945648345, 582093482214490360, 582093499402551854, 582377553478418613, 582094698747003048, 582094741690056863, 582093484373967054, 582093484355289201, 582093501530702029, 582093501551280209, 582093484377112796, 582093453769703814, 582095150805483685, 582095970057650508, 582095575996170547, 582377505183170714, 582096316883140739, 582093499938504941, 582093483806556315, 582377504644661620, 582093483836375374, 582095969521303571, 582096494040907940, 582096317949870310, 582093501000843405, 582093483804328073, 582094733641449543, 582093483282661567, 582377017143591104, 582093484371673327, 582377504629457059, 582093500470919327, 582093499411857645, 582093482214293644, 582377465968394337, 582377467040235752, 582093500452700218, 582094734723186871, 582094698471686350, 582094699279220890, 582094732038045833, 582093483279188192, 582094733111722213, 582093482733994162, 582093452696748590, 582093501530571043, 582377506794045557, 582377565828415765, 582093500994421048, 582093499402223750, 582377467579793693, 582093499923235059, 582094698743857357, 582093482207215705, 582093501555671323, 582093499399405601, 582094698745692295, 582377565829137493, 582093502078910715, 582377465970360511, 582094733641777278, 582096274996134025, 582377015538090155, 582093484907888770, 582093482749722842, 582095969528381449, 582094698206134300, 582095574919872537, 582096317430497408, 582093499402420387, 582093500458139874, 582377564751790431, 582377479388070075, 582096319564480607, 582094743303028960, 582094741690515487, 582093484340871379, 582093501525065792, 582093484376719642, 582094743311941754, 582093502096670927, 582093499415527680, 582093482213900438, 582659001095618860, 582094733113426142, 582096494577516878, 582095970056012101, 582093483814027359, 582094734714732682, 582093500490711245, 582093483267522645, 582377479388528735, 582093484876103786, 582093482741334151, 582093484877742145, 582093501020766494, 582093499407204552, 582093501544136902, 582377466504413535, 582094699282301119, 582094733104709762, 582095149191135435, 582094734718009520, 582096481156989079, 582093499927298168, 582093482218225691, 582094733109166149, 582094733104250914, 582096319567757441, 582659002167328899, 582096317418963527, 582093499402748040, 582093500988522743, 582093482765910540, 582093482746970151, 582377478850281485, 582094740621557869, 582095970596094082, 582093483804262477, 582094734182580374, 582095148656230555, 582093499957182655, 582093501545054487, 582096316884713660, 582377467576647692, 582093500987736462, 582094734177140876, 582096480082395336, 582094742236889235, 582094742227386479, 582095970595242202, 582093483835064390, 582093483283644613, 582093484904218738, 582093501566091725, 582094742768255024, 582095150266777715, 582094734177861750, 582094733111001193, 582096317942857868, 582093482733797491, 582095971135193229, 582377466507362637, 582093483805704398, 582093500483174576, 582093484893864150, 582093501003137139, 582095574382739833, 582093501024174361, 582093501568778531, 582377467044102278, 582093483813503220, 582093484341657796, 582093482730455111, 582093483304288777, 582094732569608232, 582095971675603074, 582377465970295274, 582096316874817660, 582093499390165144, 582093484368461962, 582093500459843609, 582094743306633331, 582093484882067666, 582377467042463980, 582094734182056078, 582094743306895382, 582095969526349901, 582377566365352257, 582093483821760677, 582096482227912895, 582095969520058430, 582377014464806990, 582093500479176883, 582377467577696445, 582093482755752060, 582094697670770804, 582093484369117382, 582095971130474584, 582096319026954365, 582094697667100754, 582095150803910786, 582377479389773972, 582093501564518617, 582094697676013668, 582377466506510547, 582096316872851588, 582096317965795552, 582377466504675597, 582095150266318923, 582377566365614303, 582377014469722329, 582094733639745592, 582093484374687984, 582093501001630153, 582096316882419725, 582094699285381206, 582096317430169760, 582093501533388914, 582377505199227073, 582377015539597527, 582093483808719032, 5